spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: 3000ms
server:
  port: 8081
  jetty:
    max-http-form-post-size: 10000000